website:
  title: "Francisco J. Beltrán Tapia"                       
  description: "Economic history / Historical demography"   
  image: img/fran_pic.jpg                                   
  favicon: img/favicon_dark.png                             
  
  navbar:
    pinned: true
    left:
      - text: "Publications"
        menu:
          - publications/pubs1.qmd
          - publications/pubs2.qmd
          - publications/pubs3.qmd
          - publications/pubs4.qmd
      - text: "Projects"
        menu:
          - projects/names.qmd    
          - projects/missing-girls.qmd
      - text: "Data"
        href: datasets/datasets.qmd        
      - text: "Teaching"
        href: teaching/teaching.qmd
      - text: "Bio"
        href: bio/bio.qmd
    
    right:
      - icon: bank
        href: https://www.ntnu.edu/employees/francisco.beltran.tapia
      # - icon: twitter
      # href: https://twitter.com/FJBeltranTapia
      - icon: envelope
        aria-label: email
        href: "mailto:francisco.beltran.tapia@ntnu.no"
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/fjbeltrantapia.bsky.social
  
  search: 
    location: navbar
    type: textbox
  
project:
  type: website
  output-dir: docs
  
  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - sandstone
      # - html/styles.scss
    linkcolor: $blue 
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: bottom
    reference-location: margin
    footnotes-hover: true
    link-external-newwindow: true