---
title: "Short Bio"
---

I completed an MA in Economics at the University of Zaragoza (Spain) before pursuing a PhD in History at the University of Oxford (UK). My PhD thesis, which I defended in June 2014, studied the enclosing of the commons in 19th-century Spain. I then moved to Cambridge as a Junior Research Fellow at Magdalene College. During these three years at the University of Cambridge, my research interests expanded and I started to work on inequality, education, migrants’ selectivity, agglomeration economies and gender discrimination.

Since 2017, I have been employed at the Department of Modern History and Society at the Norwegian University of Science and Technology, first as an Associate Professor (Onsager Fellow), and then as Professor of Economic History. Here I have been involved in two research projects funded by the Research Council of Norway: *Fate of Nations* (2017-2024) and *Missing girls in historical Europe*  (2020-2024). The latter, which I was the principal investigator, explores whether discriminatory practices unduly increased female mortality early in life in 19th and early-20th-century Europe. The project *What was is a name? Culture and naming practices in the past*, which I also lead, has just been granted funding by the Research Council of Norway (FRIPRO) for the period 2026-2030. 

Teaching is also a crucial component of my academic responsibilities. Since 2012, I have been teaching quantitative methods and GIS tools. Through lectures and hands-on computer sessions, my aim is to teach students with no statistical background how to apply these methods to their own research projects. I firmly believe that history students need to engage with computational tools in order to fully benefit from the ever-increasing availability of digital records, both numerical and textual.