---
title: "Publications and working papers (by topic)"
---

# Female excess mortality in infancy and childhood

[Culture, economic stress and missing girls](https://cepr.org/publications/dp18761) (Working Paper with Viktor Malein and Tamar Matiashvili)

[Life and death under son preference: Economic stress, fertility and early-life mortality in rural Spain, 1800-1910](https://ehes.org/wp/EHES_240.pdf) (Working Paper with Francisco J. Marco-Gracia and Víctor A. Luque de Haro)

[Son preference, maternal care and sex ratios at birth](https://cepr.org/publications/dp18368) (Working Paper with Rebeca Echavarri)

[Missing girls in Liberal Italy, 1861-1921](https://doi.org/10.1111/ehr.13257), *The Economic History Review* 77, 1 (2024): 185-211 (with Gabriele Cappelli)

[Economic development, female wages and missing female births in Spain, 1900-1930](https://doi.org/10.1007/s11698-023-00267-y), *Cliometrica* (2023) (with Rebeca Echavarri)

['Missing girls' in historical Europe: Reopening the debate](https://doi.org/10.1080/1081602X.2022.2132979), *The History of the Family* 27, 4 (2022): 619-657 (with Mikolaj Szoltysek)

[Infant and child sex ratios in late Imperial Russia](https://doi.org/10.1080/1081602X.2022.2098509), *The History of the Family* 27, 4 (2022): 736-763 (with Viktor Malein)

[Family patriarchy and child sex ratios in historical Europe](https://doi.org/10.1080/1081602X.2022.2051581), *The History of the Family* 27, 4 (2022): 702-735 (with Mikolaj Szoltysek, Bartosz Ogórek and Siegfried Gruber)

[Assessing gender discrimination during infancy and childhood using twins: The case of rural Spain, 1750-1950](https://doi.org/10.1080/1081602X.2022.2039878), *The History of the Family* 27, 4 (2022): 658-678 (with Francisco J. Marco-Gracia)

[Sex ratios and gender discrimination in Modern Greece](https://doi.org/10.1080/00324728.2021.1923787), *Population Studies* 76, 2 (2022): 329-346 (with Michail Raftakis).

[Inferring "missing girls" from child sex ratios in historical census data](https://doi.org/10.1080/01615440.2021.2014377), *Historical Methods: Journal of Quantitative and Interdisciplinary History* 55, 2 (2022): 98-121 (with Mikolaj Szoltysek, Bartosz Ogórek and Siegfried Gruber)

[Death, sex and fertility: Female infanticide in rural Spain, 1750-1950](https://doi.org/10.1093/ereh/heab023), *European Review of Economic History* 26, 2 (2022): 234-254 (with Francisco Marco-Gracia).

[Son preference, gender discrimination and missing girls in rural Spain, 1750-1950](https://doi.org/10.1111/padr.12406), *Population and Development Review* 47, 3 (2021): 665-687 (with Francisco Marco-Gracia).

[Sex ratios and missing girls in late-19th-century Europe](https://ehes.org/wp/EHES_160.pdf) (Working Paper).

[What explains the missing girls in 19th-century Spain?](https://doi.org/10.1111/ehr.12772), *Economic History Review* 73, 1 (2020): 59-77 (with Domingo Gallego-Martínez).

[Where are the missing girls? Gender discrimination in 19th century Spain](https://doi.org/10.1016/j.eeh.2017.08.004), *Explorations in Economic History* 66 (2017), pp. 117-126. (with Domingo Gallego-Martínez).

# Education

[Local institutions and human capital formation in pre-industrial societies: Evidence from Valencia](https://doi.org/10.1093/ereh/head022), *European Review of Economic History* (with Alfonso Díez-Minguela, Alicia Gómez-Tello, Julio Martínez-Galarraga, and Daniel Tirado-Fabregat).

[La alfabetización en el mundo urbano espanol, 1860-1930](https://www.catarata.org/libro/la-educacion-en-espana_142417/), in L.E. Otero Carvajal and S. de Miguel Salanova (eds.), *La educación en Espana. El salto adelante, 1900-1930* (Madrid: Catarata). (with Alfonso Díez-Minguela, Julio Martínez-Galarraga and Daniel Tirado-Fabregat).

[Two stories, one fate: Age-heaping and literacy in Spain, 1877-1930](https://doi.org/10.1017/S0212610921000033), *Revista de Historia Económica - Journal of Iberian and Latin American Economic History* 40, 3 (2022), pp. 405-438 (with Alfonso Díez-Minguela, Julio Martínez-Galarraga and Daniel Tirado-Fabregat).

[The uneven transition towards universal literacy in Spain, 1860-1930](https://doi.org/10.1080/0046760X.2021.1890237), *History of Education* 50, 5 (2021), pp. 605-627 (with Alfonso Díez-Minguela, Julio Martínez-Galarraga and Daniel Tirado-Fabregat).

[Class, literacy and social mobility: Madrid, 1880-1905](https://doi.org/10.1080/1081602X.2020.1853587), *The History of the Family* 26, 1 (2021), pp. 149-172 (with Santiago de Miguel Salanova).

[Capital humano y desigualdad territorial. El proceso de alfabetización en los municipios españoles desde la Ley Moyano hasta la Guerra Civil](https://www.bde.es/f/webbde/SES/Secciones/Publicaciones/PublicacionesSeriadas/EstudiosHistoriaEconomica/Fic/roja74.pdf), *Banco de España: Estudios de Historia Económica* 74, 2019 (with Alfonso Díez-Minguela, Julio Martínez-Galarraga and Daniel Tirado-Fabregat).

[Inequality and education in pre-industrial economies: Evidence from Spain](https://doi.org/10.1016/j.eeh.2017.12.003), *Explorations in Economic History* 69 (2018), pp. 81-101 (with Julio Martínez-Galarraga).

[Migrants’ self-selection in the early stages of modern economic growth, Spain (1880–1930)](https://doi.org/10.1111/ehr.12332), *Economic History Review* 70, 1 (2017), pp. 101-121 (with Santiago de Miguel Salanova).

[Enclosing literacy? Common lands and human capital in Spain, 1860-1930](https://doi.org/10.1017/S1744137413000209), *Journal of Institutional Economics* 9, 4 (2013), pp. 491-515.

# Population, inequality and economic growth

[The roots of land inequality in Spain](https://docs.google.com/viewerng/viewer?url=https://e-archivo.uc3m.es/bitstream/handle/10016/31728/wh2101.pdf) (Working Paper with Alfonso Díez-Minguela, Julio Martínez-Galarraga and Daniel Tirado-Fabregat).

[The shadow of cities: size, location and the long-term spatial distribution of population in Spain](https://doi.org/10.1007/s00168-020-01036-9), *The Annals of Regional Science* 66 (2021): 729-753 (with Julio Martínez-Galarraga and Alfonso Díez-Minguela).

[Inequality and growth in a developing economy: Evidence from regional data (Spain, 1860-1930)](https://doi.org/10.1017/ssh.2019.44), *Social Science History* 44, 1 (2020): 169-192 (with Julio Martínez-Galarraga).

[Tracing the Evolution of Agglomeration Economies: Spain, 1860-1991](https://doi.org/10.1017/S0022050718000086), *Journal of Economic History* 78, 1 (2018), pp. 81-117 (with Alfonso Díez-Minguela and Julio Martínez-Galarraga).

# Agricultural Development

[Revisiting Allen's nitrogen hypothesis from a climate perspective (1645-1740)](https://repositori.uji.es/xmlui/bitstream/handle/10234/182881/DT-SEHA%201902.pdf?sequence=1&isAllowed=y) (Working Paper with José Luis Martínez-González).

[Communal hopes and land reform in rural Spain, 1931-1936] (with Iñaki Iriarte and José Miguel Lana).

[En torno al comunal en España: Una agenda de investigación llena de retos y promesas](https://puz.unizar.es/2006-del-pasado-al-futuro-como-problema-la-historia-agraria-contemporanea-espanola-en-el-siglo-xxi.html), in D. Soto Fernández and J.M. Lana Berasáin (eds.), *Del pasado al futuro como problema: La historia agraria contemporánea española en el siglo XXI* (Zaragoza: Prensas Universitarias de Zaragoza, 2018: pp. 145-162) ([link](https://repositori.uji.es/xmlui/bitstream/handle/10234/176624/DT-SEHA-1804.pdf?sequence=1&isAllowed=y) to the working paper).

[Common lands and economic development in Spain](https://doi.org/10.1017/S0212610915000269), *Revista de Historia Económica - Journal of Iberian and Latin American Economic History* 34, 1 (2016), pp. 111-133.

[Commons and the standard of living debate in Spain, 1860-1930](https://doi.org/10.1007/s11698-014-0107-9), *Cliometrica* 9, 1 (2015), pp. 27-48.

["Goth and Vandals" or "Civilised" peasants? Common lands and agricultural productivity in Spain, 1900-1930](https://doi.org/10.1017/ssh.2015.52), *Social Science History* 39, 2 (2015), pp. 217-252.

[Social and environmental filters to market incentives: Common land persistence in 19th century Spain](https://doi.org/10.1111/joac.12056), *Journal of Agrarian Change* 15, 2 (2015), pp. 239-260.

[Commons, Social Capital and the Emergence of Agricultural Cooperatives in Early 20th Century Spain](https://doi.org/10.1093/ereh/hes014), *European Review of Economic History* 16 (2012), pp. 511-528.

