---
title: "Education"
---

[What was in a name? Culture, naming practices and literacy](https://cepr.org/publications/dp19625) (Working Paper with Francisco J. Marco-Gracia)

[Local institutions and human capital formation in pre-industrial societies: Evidence from Valencia](https://doi.org/10.1093/ereh/head022), *European Review of Economic History* 28, 2 (2024): 135–162 (with Alfonso Díez-Minguela, Alicia Gómez-Tello, Julio Martínez-Galarraga, and Daniel Tirado-Fabregat).

[La alfabetización en el mundo urbano español, 1860-1930](https://www.catarata.org/libro/la-educacion-en-espana_142417/), in L.E. Otero Carvajal and S. de Miguel Salanova (eds.), *La educación en España. El salto adelante, 1900-1930* (Madrid: Catarata). (with Alfonso Díez-Minguela, Julio Martínez-Galarraga and Daniel Tirado-Fabregat).

[Two stories, one fate: Age-heaping and literacy in Spain, 1877-1930](https://doi.org/10.1017/S0212610921000033), *Revista de Historia Económica - Journal of Iberian and Latin American Economic History* 40, 3 (2022): 405–438 (with Alfonso Díez-Minguela, Julio Martínez-Galarraga and Daniel Tirado-Fabregat).

[The uneven transition towards universal literacy in Spain, 1860-1930](https://doi.org/10.1080/0046760X.2021.1890237), *History of Education* 50, 5 (2021): 605–627 (with Alfonso Díez-Minguela, Julio Martínez-Galarraga and Daniel Tirado-Fabregat).

[Class, literacy and social mobility: Madrid, 1880-1905](https://doi.org/10.1080/1081602X.2020.1853587), *The History of the Family* 26, 1 (2021): 149–172 (with Santiago de Miguel Salanova).

[Capital humano y desigualdad territorial. El proceso de alfabetización en los municipios españoles desde la Ley Moyano hasta la Guerra Civil](https://www.bde.es/f/webbde/SES/Secciones/Publicaciones/PublicacionesSeriadas/EstudiosHistoriaEconomica/Fic/roja74.pdf), *Banco de España: Estudios de Historia Económica* 74, 2019 (with Alfonso Díez-Minguela, Julio Martínez-Galarraga and Daniel Tirado-Fabregat).

[Inequality and education in pre-industrial economies: Evidence from Spain](https://doi.org/10.1016/j.eeh.2017.12.003), *Explorations in Economic History* 69 (2018): 81–101 (with Julio Martínez-Galarraga).

[Migrants’ self-selection in the early stages of modern economic growth, Spain (1880–1930)](https://doi.org/10.1111/ehr.12332), *Economic History Review* 70, 1 (2017): 101–121 (with Santiago de Miguel Salanova).

[Enclosing literacy? Common lands and human capital in Spain, 1860-1930](https://doi.org/10.1017/S1744137413000209), *Journal of Institutional Economics* 9, 4 (2013): 491–515.