---
title: "Gender discrimination early in life (missing girls)"
---

[Culture, economic stress and missing girls](https://cepr.org/publications/dp18761) (Working Paper with Viktor Malein and Tamar Matiashvili)

[Pre-natal care, son preference and the sex ratio at birth](https://doi.org/10.1215/00703370-11798263), *Demography* (with Rebeca Echavarri)

[Life and death under son preference: Economic stress, fertility and early-life mortality in rural Spain, 1800-1910](https://doi.org/10.1017/S0956793324000244), *Rural History* (with Francisco J. Marco-Gracia and Víctor A. Luque de Haro)

[Missing girls in Liberal Italy, 1861-1921](https://doi.org/10.1111/ehr.13257), *The Economic History Review* 77, 1 (2024): 185-211 (with Gabriele Cappelli)

[Economic development, female wages and missing female births in Spain, 1900-1930](https://doi.org/10.1007/s11698-023-00267-y), *Cliometrica* (2023) (with Rebeca Echavarri)

['Missing girls' in historical Europe: Reopening the debate](https://doi.org/10.1080/1081602X.2022.2132979), *The History of the Family* 27, 4 (2022): 619-657 (with Mikolaj Szoltysek)

[Infant and child sex ratios in late Imperial Russia](https://doi.org/10.1080/1081602X.2022.2098509), *The History of the Family* 27, 4 (2022): 736-763 (with Viktor Malein)

[Family patriarchy and child sex ratios in historical Europe](https://doi.org/10.1080/1081602X.2022.2051581), *The History of the Family* 27, 4 (2022): 702-735 (with Mikolaj Szoltysek, Bartosz Ogórek and Siegfried Gruber)

[Assessing gender discrimination during infancy and childhood using twins: The case of rural Spain, 1750-1950](https://doi.org/10.1080/1081602X.2022.2039878), *The History of the Family* 27, 4 (2022): 658-678 (with Francisco J. Marco-Gracia)

[Sex ratios and gender discrimination in Modern Greece](https://doi.org/10.1080/00324728.2021.1923787), *Population Studies* 76, 2 (2022): 329-346 (with Michail Raftakis).

[Inferring "missing girls" from child sex ratios in historical census data](https://doi.org/10.1080/01615440.2021.2014377), *Historical Methods: Journal of Quantitative and Interdisciplinary History* 55, 2 (2022): 98-121 (with Mikolaj Szoltysek, Bartosz Ogórek and Siegfried Gruber)

[Death, sex and fertility: Female infanticide in rural Spain, 1750-1950](https://doi.org/10.1093/ereh/heab023), *European Review of Economic History* 26, 2 (2022): 234-254 (with Francisco Marco-Gracia).

[Son preference, gender discrimination and missing girls in rural Spain, 1750-1950](https://doi.org/10.1111/padr.12406), *Population and Development Review* 47, 3 (2021): 665-687 (with Francisco Marco-Gracia).

[Sex ratios and missing girls in late-19th-century Europe](https://ehes.org/wp/EHES_160.pdf) (Working Paper).

[What explains the missing girls in 19th-century Spain?](https://doi.org/10.1111/ehr.12772), *Economic History Review* 73, 1 (2020): 59-77 (with Domingo Gallego-Martínez).

[Where are the missing girls? Gender discrimination in 19th century Spain](https://doi.org/10.1016/j.eeh.2017.08.004), *Explorations in Economic History* 66 (2017), pp. 117-126. (with Domingo Gallego-Martínez).